import { BPMFSymbol, Consonant, Medial, Rhyme, Tone } from './bpmf.enum';
import { Layout } from './layout.models';

export const BPMF_LAYOUT: Layout<BPMFSymbol | string> = {
  left: {
    thumbEnd: {
      e: Consonant.B,
      s: Consonant.P,
      w: Consonant.M,
      n: Consonant.F,
    },
    thumbMid: {
      e: Consonant.D,
      s: Consonant.T,
      w: Consonant.N,
      n: Consonant.L,
    },
    thumbTip: { e: Consonant.G, s: Consonant.K, w: Consonant.H, n: 'v' },
    index: { e: Consonant.J, s: Consonant.Q, w: Consonant.X, n: '⌫' },
    middle: {
      e: Consonant.ZH,
      s: Consonant.CH,
      w: Consonant.SH,
      n: Consonant.R,
    },
    ring: { e: Consonant.Z, s: Consonant.C, w: Consonant.S, n: '⌃' },
  },
  right: {
    index: { w: Medial.I, s: Medial.U, e: Tone.Tone1, n: '⌤' },
    thumbEnd: { w: Rhyme.A, s: Rhyme.O, e: Rhyme.ER, n: Rhyme.E },
    thumbMid: { w: Rhyme.AI, s: Rhyme.EI, n: Rhyme.AO, e: 'dup' },
    thumbTip: { w: Rhyme.OU, s: Rhyme.AN, e: Rhyme.EN, n: Rhyme.ANG },
    middle: { w: Medial.UE, s: Tone.Tone2, e: Tone.Tone3, n: Tone.Tone4 },
    ring: { w: Rhyme.ERR, s: Rhyme.ENG, e: Tone.Tone5, n: '⌃' },
  },
};

export const DEFAULT_LAYOUT: Layout<string> = {
  left: {
    thumbEnd: { e: '/', s: '(L)⎋', w: 'LW', n: '-' },
    thumbMid: { e: 'w', s: 'z', w: 'g', n: 'LC' },
    thumbTip: { e: 'k', s: 'c', w: 'm', n: 'v' },
    index: { e: 'r', s: 'e', w: '(L)␣', n: '⌫' },
    middle: { e: 'i', s: 'o', w: '.', n: 'delete' },
    ring: { e: "'", s: 'u', w: ',', n: '⌃' },
    ringMid: { e: 'LMR', s: 'LMD', w: 'LML', n: 'LMU' },
  },
  right: {
    thumbEnd: { w: 'RC', s: '(R)⎋', e: 'RW', n: '?' },
    thumbMid: { w: 'b', s: 'q', e: 'dup', n: 'x' },
    thumbTip: { w: 'f', s: 'd', e: 'h', n: 'p' },
    index: { w: 'a', s: 't', e: '(R)␣', n: '⌤' },
    middle: { w: 'l', s: 'n', e: 'j', n: '⇥' },
    ring: { w: 'y', s: 's', e: ';', n: '⌃' },
    ringMid: { e: 'RMR', s: 'RMD', w: 'RML', n: 'RMU' },
  },
};

export const NEED_REMAP_KEYS: string[] = [
  'delete',
  '(L)␣',
  'LC',
  'RC',
  'LW',
  '(L)⎋',
  'RC',
  '(R)⎋',
  'RW',
  '⇥',
  'LML',
  'LMD',
  'RMU',
  'RMR',
  'RMD',
];

export const REMAPPED_LAYOUT: Layout<string> = {
  left: {
    thumbEnd: { e: '/', s: '[', w: '(', n: '-' },
    thumbMid: { e: 'w', s: 'z', w: 'g', n: '#' },
    thumbTip: { e: 'k', s: 'c', w: 'm', n: 'v' },
    index: { e: 'r', s: 'e', w: '|', n: '⌫' },
    middle: { e: 'i', s: 'o', w: '.', n: '{' },
    ring: { e: "'", s: 'u', w: ',', n: '⌃' },
    ringMid: { e: '<', s: '+', w: 'LW', n: '=' },
  },
  right: {
    thumbEnd: { w: '$', s: ']', e: ')', n: '?' },
    thumbMid: { w: 'b', s: 'q', e: 'dup', n: 'x' },
    thumbTip: { w: 'f', s: 'd', e: 'h', n: 'p' },
    index: { w: 'a', s: 't', e: '(R)␣', n: '⌤' },
    middle: { w: 'l', s: 'n', e: 'j', n: '}' },
    ring: { w: 'y', s: 's', e: ';', n: '⌃' },
    ringMid: { w: '>', s: '⎋', e: 'RW', n: '⇥' },
  },
};

export const KEY_TO_SYMBOL = new Map<string, BPMFSymbol>([
  ['/', Consonant.B],
  ['[', Consonant.P],
  ['(', Consonant.M],
  ['-', Consonant.F],
  ['w', Consonant.D],
  ['z', Consonant.T],
  ['g', Consonant.N],
  ['#', Consonant.L],
  ['k', Consonant.G],
  ['c', Consonant.K],
  ['m', Consonant.H],
  ['r', Consonant.J],
  ['e', Consonant.Q],
  ['|', Consonant.X],
  ['i', Consonant.ZH],
  ['o', Consonant.CH],
  ['.', Consonant.SH],
  ['{', Consonant.R],
  ["'", Consonant.Z],
  ['u', Consonant.C],
  [',', Consonant.S],
  ['a', Medial.I],
  ['t', Medial.U],
  ['l', Medial.UE],
  ['$', Rhyme.A],
  [']', Rhyme.O],
  [')', Rhyme.ER],
  ['?', Rhyme.E],
  ['b', Rhyme.AI],
  ['q', Rhyme.EI],
  ['x', Rhyme.AO],
  ['f', Rhyme.OU],
  ['d', Rhyme.AN],
  ['h', Rhyme.EN],
  ['p', Rhyme.ANG],
  ['s', Rhyme.ENG],
  ['y', Rhyme.ERR],
  [' ', Tone.Tone1],
  ['n', Tone.Tone2],
  ['j', Tone.Tone3],
  ['}', Tone.Tone4],
  [';', Tone.Tone5],
]);
